version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-rc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17ml5gk3w9l5b"
s3_prefix = "cloud-rc"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
